### ISSUE TITLE
Gives false links

### ISSUE THREAD

**Issue by Gildian** [Gildian/WikipediaGame#2] opened 2024-02-25 22:24 UTC
Output of all the search functions gives links that could not be traversed.

**Comment by sMattGuy** [comment] 2024-02-26 14:28
Issue is caused by links at the bottom of the page under the "See More" section, which needs to be filtered out since it violates the rules of the game.

**Comment by sMattGuy** [comment] 2024-02-26 20:43
Issue resolved in newest branch issue-2-fix but this has caused many new issues. Do not merge with main

**Closed as completed by sMattGuy** 2024-02-26 20:43 UTC
